version: '3'
services:
  chat-copilot-web:
    image: chat-copilot-web
    build: 
      context: ..
      dockerfile: docker/webapp/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ../webapp/.env
    depends_on:
      chat-copilot-api:
        condition: service_started
  chat-copilot-api:
    image: chat-copilot-api
    build: 
      context: ..
      dockerfile: docker/webapi/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ../webapi/.env
    environment:
      - MemoryStore__Qdrant__Host=http://qdrant
    depends_on:
      qdrant:
        condition: service_started
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333

