apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-nodependson.yaml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: max-copilot-webapi
  name: max-copilot-webapi
spec:
  ports:
    - name: "3080"
      port: 3080
      targetPort: 8080
  selector:
    io.kompose.service: max-copilot-webapi
status:
  loadBalancer: {}
