apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-nodependson.yaml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: qdrant
  name: qdrant
spec:
  ports:
    - name: "6333"
      port: 6333
      targetPort: 6333
  selector:
    io.kompose.service: qdrant
status:
  loadBalancer: {}
