name: copilot-deploy-pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/copilot-build-backend.yml

  deploy-int-infra:
    uses: ./.github/workflows/copilot-deploy-infra.yml
    with:
      ENVIRONMENT: int
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      WEB_API_KEY: ${{secrets.WEB_API_KEY}}
      AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}

  deploy-int-binaries:
    needs: [build, deploy-int-infra]
    uses: ./.github/workflows/copilot-deploy-binaries.yml
    with:
      ENVIRONMENT: int
      ARTIFACT_NAME: ${{needs.build.outputs.artifact}}
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      WEB_API_KEY: ${{secrets.WEB_API_KEY}}
      AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}
      APPLICATION_AUTHORITY: ${{secrets.APPLICATION_AUTHORITY}}

  deploy-stable-infra:
    needs: deploy-int-binaries
    uses: ./.github/workflows/copilot-deploy-infra.yml
    with:
      ENVIRONMENT: stable
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      WEB_API_KEY: ${{secrets.WEB_API_KEY}}
      AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}

  deploy-stable-binaries:
    uses: ./.github/workflows/copilot-deploy-binaries.yml
    needs: deploy-stable-infra
    with:
      ENVIRONMENT: stable
      ARTIFACT_NAME: ${{needs.build.outputs.artifact}}
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      WEB_API_KEY: ${{secrets.WEB_API_KEY}}
      AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}
      APPLICATION_AUTHORITY: ${{secrets.APPLICATION_AUTHORITY}}
