name: Build and deploy to Azure Kubernetes Service

env:
  RESOURCE_GROUP: MY_RESOURCE_GROUP # set this to the resource group containing your AKS cluster
  CLUSTER_NAME: MY_CLUSTER_NAME # set this to the name of your AKS cluster
  CHART_PATH: MY_HELM_FILE # set this to the path to your helm file
  CHART_OVERRIDE_PATH: MY_OVERRIDE_FILES # set this to an array of override file paths

on:
  push:
  workflow_dispatch: # deploy on demand
    inputs:
      environment_name:
        description: "Which environment to deploy to?"
        type: choice # drop-down menus are fantastic!
        required: true
        options: # change these to your own names or change :point_up: to a `string` for freeform entry.
          - "dev"
          - "test"
          - "prod"
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Gets K8s context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
        id: login

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Update Helm deployment
        run: |
          helm upgrade --install ${{ github.event.inputs.environment_name }} \
          --namespace "copilot-${{ github.event.inputs.environment_name }}" \
          -f helm/values-${{ github.event.inputs.environment_name}}.yaml \
          -f helm/values.yaml \
          helm/
