name: Build CopilotChatMemoryPipelineService

on:
  pull_request:
    branches: ["main"]
    paths:
      - "memorypipeline/**"

permissions:
  contents: read

jobs:
  memory-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Set .Net Core version
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build CopilotChatMemoryPipelineService
        run: |
          dotnet build memorypipeline/CopilotChatMemoryPipeline.csproj \
            -c Release \
            -v normal
